#   WHEEL > Config > Databases
#   --------------------------
#
#   Databases configuration

# Name of the default configuration
# If empty, no autoLoad
defaultConfig: 'default'

# Configurations ------------------

-default
    host: 'localhost'
    user: 'root'
    pass: 'password'
    dbname: 'database'
    encoding: utf8